using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace YoutubeExplode.Internal.Decoders
{
    internal partial class VideoInfoDecoder : DecoderBase
    {
        private readonly IReadOnlyDictionary<string, string> _root;

        public VideoInfoDecoder(IReadOnlyDictionary<string, string> root)
        {
            _root = root;
        }

        public bool Validate() => Cache(() => !_root.GetValueOrDefault("video_id").IsNullOrWhiteSpace());

        public string TryGetErrorReason() => Cache(() => _root.GetValueOrDefault("reason"));

        public string TryGetPreviewVideoId() => Cache(() =>
            GetPlayerResponse().SelectToken("playabilityStatus.errorScreen.playerLegacyDesktopYpcTrailerRenderer.trailerVideoId")
                ?.Value<string>());

        public string GetVideoAuthor() => Cache(() => GetPlayerResponse().SelectToken("videoDetails.author").Value<string>());

        public string GetChannelId() => Cache(() => GetPlayerResponse().SelectToken("videoDetails.channelId").Value<string>());

        public string GetVideoTitle() => Cache(() => GetPlayerResponse().SelectToken("videoDetails.title").Value<string>());

        public TimeSpan GetVideoDuration() => Cache(() =>
        {
            var durationSeconds = GetPlayerResponse().SelectToken("videoDetails.lengthSeconds").Value<double>();
            return TimeSpan.FromSeconds(durationSeconds);
        });

        public IReadOnlyList<string> GetVideoKeywords() =>
            Cache(() => GetPlayerResponse().SelectToken("videoDetails.keywords").EmptyIfNull().Values<string>().ToArray());

        public string TryGetDashManifestUrl() => Cache(() => _root.GetValueOrDefault("dashmpd"));

        public string TryGetHlsManifestUrl() => Cache(() => _root.GetValueOrDefault("hlsvp"));

        private JToken GetPlayerResponse() => Cache(() =>
        {
            var playerResponseRaw = _root["player_response"];
            return JToken.Parse(playerResponseRaw);
        });

        public TimeSpan GetExpiresIn() => Cache(() =>
        {
            var expiresInSeconds = GetPlayerResponse().SelectToken("streamingData.expiresInSeconds").Value<double>();
            return TimeSpan.FromSeconds(expiresInSeconds);
        });

        public IEnumerable<ClosedCaptionTrackInfoDecoder> GetClosedCaptionTrackInfos() =>
            Cache(() => GetPlayerResponse().SelectToken("captions.playerCaptionsTracklistRenderer.captionTracks").EmptyIfNull()
                .Select(t => new ClosedCaptionTrackInfoDecoder(t)));

        public IReadOnlyList<StreamInfoDecoder> GetMuxedStreamInfos() => Cache(() =>
        {
            var streamInfosEncoded = _root.GetValueOrDefault("url_encoded_fmt_stream_map");

            if (streamInfosEncoded.IsNullOrWhiteSpace())
                return new StreamInfoDecoder[0];

            return streamInfosEncoded.Split(",")
                .Select(UrlEx.SplitQuery)
                .Select(d => new StreamInfoDecoder(d))
                .ToArray();
        });

        public IReadOnlyList<StreamInfoDecoder> GetAdaptiveStreamInfos() => Cache(() =>
        {
            var streamInfosEncoded = _root.GetValueOrDefault("adaptive_fmts");

            if (streamInfosEncoded.IsNullOrWhiteSpace())
                return new StreamInfoDecoder[0];

            return streamInfosEncoded.Split(",")
                .Select(UrlEx.SplitQuery)
                .Select(d => new StreamInfoDecoder(d))
                .ToArray();
        });
    }

    internal partial class VideoInfoDecoder
    {
        public class ClosedCaptionTrackInfoDecoder : DecoderBase
        {
            private readonly JToken _root;

            public ClosedCaptionTrackInfoDecoder(JToken root)
            {
                _root = root;
            }

            public string GetUrl() => Cache(() => _root.SelectToken("baseUrl").Value<string>());

            public string GetLanguageCode() => Cache(() => _root.SelectToken("languageCode").Value<string>());

            public string GetLanguageName() => Cache(() => _root.SelectToken("name.simpleText").Value<string>());

            public bool GetIsAutoGenerated() => Cache(() =>
                _root.SelectToken("vssId").Value<string>().StartsWith("a.", StringComparison.OrdinalIgnoreCase));
        }
    }

    internal partial class VideoInfoDecoder
    {
        public static VideoInfoDecoder Initialize(string raw)
        {
            var root = UrlEx.SplitQuery(raw);
            return new VideoInfoDecoder(root);
        }
    }
}