using System;
using Newtonsoft.Json.Linq;

namespace YoutubeExplode.Internal.Parsers
{
    internal class ClosedCaptionTrackInfoParser : Cached
    {
        private readonly JToken _root;

        public ClosedCaptionTrackInfoParser(JToken root)
        {
            _root = root;
        }

        public string GetUrl() => Cache(() => _root.SelectToken("baseUrl").Value<string>());

        public string GetLanguageCode() => Cache(() => _root.SelectToken("languageCode").Value<string>());

        public string GetLanguageName() => Cache(() => _root.SelectToken("name.simpleText").Value<string>());

        public bool GetIsAutoGenerated() => Cache(() =>
            _root.SelectToken("vssId").Value<string>().StartsWith("a.", StringComparison.OrdinalIgnoreCase));
    }
}