using System;
using System.Text.Json;
using YoutubeExplode.Utils;
using YoutubeExplode.Utils.Extensions;

namespace YoutubeExplode.Extraction.Responses
{
    internal class PlayerClosedCaptionTrackInfoResponse
    {
        private readonly JsonElement _root;
        private readonly Memo _memo = new();

        public PlayerClosedCaptionTrackInfoResponse(JsonElement root) => _root = root;

        public string? TryGetUrl() => _memo.Wrap(() =>
            _root
                .GetPropertyOrNull("baseUrl")?
                .GetStringOrNull()
        );

        public string? TryGetLanguageCode() => _memo.Wrap(() =>
            _root
                .GetPropertyOrNull("languageCode")?
                .GetStringOrNull()
        );

        public string? TryGetLanguageName() => _memo.Wrap(() =>
            _root
                .GetPropertyOrNull("name")?
                .GetPropertyOrNull("simpleText")?
                .GetStringOrNull()
        );

        public bool IsAutoGenerated() => _memo.Wrap(() =>
            _root
                .GetPropertyOrNull("vssId")?
                .GetStringOrNull()?
                .StartsWith("a.", StringComparison.OrdinalIgnoreCase) ?? false
        );
    }
}