using System;
using System.Linq;
using System.Text.Json;
using YoutubeExplode.Utils;
using YoutubeExplode.Utils.Extensions;

namespace YoutubeExplode.Bridge;

internal class PlayerClosedCaptionTrackInfoExtractor
{
    private readonly JsonElement _content;
    private readonly Memo _memo = new();

    public PlayerClosedCaptionTrackInfoExtractor(JsonElement content) => _content = content;

    public string? TryGetUrl() => _memo.Wrap(() =>
        _content
            .GetPropertyOrNull("baseUrl")?
            .GetStringOrNull()
    );

    public string? TryGetLanguageCode() => _memo.Wrap(() =>
        _content
            .GetPropertyOrNull("languageCode")?
            .GetStringOrNull()
    );

    public string? TryGetLanguageName() => _memo.Wrap(() =>
        _content
            .GetPropertyOrNull("name")?
            .GetPropertyOrNull("simpleText")?
            .GetStringOrNull() ??

        _content
            .GetPropertyOrNull("name")?
            .GetPropertyOrNull("runs")?
            .EnumerateArrayOrNull()?
            .Select(j => j.GetPropertyOrNull("text")?.GetStringOrNull())
            .WhereNotNull()
            .ConcatToString()
    );

    public bool IsAutoGenerated() => _memo.Wrap(() =>
        _content
            .GetPropertyOrNull("vssId")?
            .GetStringOrNull()?
            .StartsWith("a.", StringComparison.OrdinalIgnoreCase) ?? false
    );
}