namespace YoutubeExplode.Models
{
    /// <summary>
    /// Closed captions meta data
    /// </summary>
    public class ClosedCaptionTrackInfo
    {
        /// <summary>
        /// URL for this caption track's manifest
        /// </summary>
        public string Url { get; internal set; }

        /// <summary>
        /// Language of this caption track
        /// </summary>
        public string Language { get; internal set; }

        /// <summary>
        /// Whether this caption track was generated automatically
        /// </summary>
        public bool IsAutoGenerated { get; internal set; }

        internal ClosedCaptionTrackInfo() { }

        /// <inheritdoc />
        public override string ToString()
        {
            if (IsAutoGenerated)
                return $"{Language} (auto)";
            return $"{Language}";
        }
    }
}