using System.Globalization;

namespace YoutubeExplode.Models
{
    /// <summary>
    /// Closed caption track metadata
    /// </summary>
    public class ClosedCaptionTrackInfo
    {
        /// <summary>
        /// URL for this caption track's manifest
        /// </summary>
        public string Url { get; internal set; }

        /// <summary>
        /// This closed caption track's culture
        /// </summary>
        public CultureInfo Culture { get; internal set; }

        /// <summary>
        /// Whether this caption track was generated automatically
        /// </summary>
        public bool IsAutoGenerated { get; internal set; }

        internal ClosedCaptionTrackInfo() { }

        /// <inheritdoc />
        public override string ToString()
        {
            if (IsAutoGenerated)
                return $"{Culture.EnglishName} (auto)";
            return $"{Culture.EnglishName}";
        }
    }
}