namespace YoutubeExplode.Models
{
    /// <summary>
    /// Closed captions meta data
    /// </summary>
    public class VideoCaptionTrackInfo
    {
        /// <summary>
        /// URL for the caption track manifest
        /// </summary>
        public string Url { get; internal set; }

        /// <summary>
        /// Caption track language
        /// </summary>
        public string Language { get; internal set; }

        /// <summary>
        /// Whether this caption track was generated automatically
        /// </summary>
        public bool IsAutoGenerated { get; internal set; }

        internal VideoCaptionTrackInfo() { }

        /// <inheritdoc />
        public override string ToString()
        {
            if (IsAutoGenerated)
                return $"{Language} (auto)";
            return $"{Language}";
        }
    }
}