namespace YoutubeExplode.Videos.ClosedCaptions
{
    public class ClosedCaptionTrackInfo
    {
        public string Url { get; }

        /// <summary>
        /// Language of the associated track.
        /// </summary>
        public Language Language { get; }

        /// <summary>
        /// Whether the associated track was automatically generated.
        /// </summary>
        public bool IsAutoGenerated { get; }

        public ClosedCaptionTrackInfo(string url, Language language, bool isAutoGenerated)
        {
            Url = url;
            Language = language;
            IsAutoGenerated = isAutoGenerated;
        }

        /// <inheritdoc />
        public override string ToString() => $"CC Track ({Language})";
    }
}